### ISSUE TITLE
Minifying issue with CSS

### ISSUE THREAD

**Issue by amerllica** [terser/html-minifier-terser#64]
Unfortunately, `html-minifier-terser` during minifying with the `minifyCSS: true,` we faced this issue. my code is like this:

```css
div * {
  color: red;
}
```
Bu my code is changed to this:

```css
div*{color:red}
```

And browser cannot understand this selector `div*` it should be `div *`, even in the production level after minifying, is there any property for preventing that issue or is it a bug?

**Comment by DanielRuf** [comment]
Please report this issue at https://github.com/clean-css/clean-css because html-minifier and html-minifier use this to compress css code.

Also test with clean-css 5. If this happens only in clean-css 4, then we will have to upgrade to clean-css 5. See also https://github.com/kangax/html-minifier/pull/1098

**Comment by DanielRuf** [comment]
> And browser cannot understand this selector `div*` it should be `div *`, even in the production level after minifying, is there any property for preventing that issue or is it a bug?

If you want to prevent this for some code blocks, clean-css has a solution for this:
https://github.com/clean-css/clean-css#how-to-keep-a-css-fragment-intact

> Wrap the CSS fragment in special comments which instruct clean-css to preserve it, e.g.

```css
.block-1 {
  color: red
}
/* clean-css ignore:start */
.block-special {
  color: transparent
}
/* clean-css ignore:end */
.block-2 {
  margin: 0
}
```
